- src/App.jsx
> hello guys

- package-lock.json
- package.json
- postcss.config.js
- src/App.jsx
- src/Components/LogIn page/LeftModel.jsx
- src/index.css
- tailwind.config.js
Tailwind Css added
cc- @Sayanipal2004 @TitlyC06 @PayalRoy2004
> Tailwind Css configaration

- index.html
- package-lock.json
- package.json
- src/Components/LogIn page/LeftModel.jsx
> MUI config

- src/App.jsx
- src/Components/LogIn page/RightModel/Input.jsx
Hi @Sabbir45ali @subhratanuSaha
please review and merge this PR 
RightModal form is done
cc- @TitlyC06 @PayalRoy2004
> RightModal form done

- src/App.jsx
- src/Components/LogIn page/RightModel/Input.jsx
- src/Components/LogIn page/RightModel/MainRightModel.jsx
- src/Components/LogIn page/RightModel/RightButton.jsx
Hi @Sabbir45ali @ShubhratanuSaha
Please review and merge this pr 
CC- @Sayanipal2004  @PayalRoy2004
> RightButtonAdded

- src/Components/LogIn page/RightModel/MainRightModel.jsx
- src/Components/LogIn page/RightModel/RightButton.jsx
- src/Components/LogIn page/RightModel/RightHeader.jsx
Hi @Sabbir45ali @SubhratanuSaha
CC- @TitlyC06 @PayalRoy2004
> RightHeader added

- src/Components/LogIn page Component/LoginPageRightModel/Header.jsx
- src/Components/LogIn page Component/LoginPageRightModel/MainRightModel.jsx
- src/Components/LogIn page Component/LoginPageRightModel/RightButton.jsx
Hi @Sabbir45ali @Subhratanusaha
CC- @TitlyC06 @PayalRoy2004
> props added in Header and MainRightModel

- src/App.jsx
- src/Components/LogIn page Component/LoginPageRightModel/Input.jsx
- src/Components/LogIn page Component/LoginPageRightModel/MainRightModel.jsx
Hii @SubhratanuSaha
Right modal updated
cc- @JOY-Singha-03 @PayalRoy2004 @TitlyC06 @Sayanipal2004
> Update routing and enhance layout for login components

- src/App.jsx
- src/Components/Signup page Component/signupinput.jsx
- src/pages/signuppage/Signup.jsx
Hi @Sabbir45ali @subhratanusaha
Sign-up page form done, state changing will done by @Sayanipal2004 .
CC- @PayalRoy2004  @JOY-Singha-03  @Sayanipal2004
> signup page form done

- src/App.jsx
- src/Components/LogIn page Component/LoginPageLeftModel/LeftModel.jsx
- src/Components/LogIn page Component/LoginPageRightModel/UniversalButton.jsx
- src/pages/LoginPage/Login.jsx
- src/pages/signuppage/Signup.jsx
Hi @Subhratanu @Sabbir45ali 
I have included conditional rendering and state management using useState in the "Login" and "SignUp" page. The onClick event is handled by the "UniversalButton" and the event is passed in the "LeftModel" through props for state-based page transition and sliding animation.
CC- @PayalRoy2004 @TitlyC06
> State changing in the login page is done

- src/App.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_Footer.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_bg.jsx
- src/pages/SignInPage_Mobile/SignINPage_Mobile.jsx
Hi!
@Subhratanu @Sabbir45ali 
CC- @JOY-Singha-03 @PayalRoy2004 @TitlyC06
> SignINPage_Mobile Complete

- index.html
Hi, @Subhratanu @EmrysILIO1710 @Sabbir45ali 
Title of the project is corrected.
Please review and close the issue (BUG-0002)
CC- @JOY-Singha-03 @PayalRoy2004 @TitlyC06
> Title of the project is corrected to 'Breast-Cancer-Detection'

- src/Components/Signup page Component/SignUpPageLeftModal.jsx
Hi, @Subhratanu @EmrysILIO1710 @Sabbir45ali 
Spelling of SIGN-UP button in SignInMobile page is fixed
Please review and close the issue (BUG-0004)
CC- @JOY-Singha-03 @PayalRoy2004 @TitlyC06
> Spelling of SIGN-UP is fixed

- src/Components/SignInPage_Mobile_Components/SignInPage_bg.jsx
Hi, @Subhratanu @Sabbir45ali @EmrysILIO1710 
Cross icon added in the SignInMobile page
Please review and close the issue (BUG-0007)
cc- @JOY-Singha-03 @PayalRoy2004 @TitlyC06
> cross icon added on the SignIn Mobile page

- src/App.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_Button.jsx
- vite.config.js
Hi @Subhratanu @EmrysILIO1710 
URL problem fixed with routing.
please Review and close this Issue ( BUG-0001 ).
> fix: switch from HashRouter to BrowserRouter and update route path

- src/Components/LogIn page Component/LoginPageRightModel/Input.jsx
- src/Components/SignInPage_Mobile_Components/SignInPageInput.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_Footer.jsx
- src/pages/Mobile_LandingPage/Mobile_landingPage.jsx
- src/pages/SignUpPageMobile/SignUpPageMobile.jsx
- src/pages/signuppage/Signup.jsx
Hii @EmrysILIO1710 @Subhratanu 
Signup Box position fixed.
please review and close this issue.
> fix: enhance input components with password visibility toggle and improve layout

- src/Components/Home Page Components/Header.jsx
- src/Components/HomePageMobileComponents/FooterMobile.jsx
- src/Components/HomePageMobileComponents/NavbarMobile.jsx
- src/Components/LogIn page Component/LoginPageLeftModel/LeftModel.jsx
- src/Components/LogIn page Component/LoginPageRightModel/LoginButton.jsx
- src/Components/LogIn page Component/LoginPageRightModel/RightButton.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_Footer.jsx
- src/Components/Signup page Component/SignUpPageLeftModal.jsx
- src/Components/Signup page Component/SignupButton.jsx
- src/Components/Universal Components/Navbar.jsx
- src/Components/Universal Components/ProfileIcon.jsx
- src/pages/HomePage/HomePage.jsx
- src/pages/HomePage_Mobile/HomePage_Mobile.jsx
- src/pages/ProfilePage/Profile.jsx
Hi @Subhratanu @EmrysILIO1710 @Sabbir45ali
CC- @Sayanipal2004 @JOY-Singha-03 @PayalRoy2004
> Color Updated

- src/Components/Profile Page Components/ProfileNav.jsx
- src/pages/ProfilePage/Profile.jsx
hiii
@Subhratanu @EmrysILIO1710 @Sabbir45ali 
please review and merge this PR.
cc: @Sayanipal2004 @TitlyC06
> navbar added in profile page (desktop)

- src/Components/Profile Page Components/PersonalInfo.jsx
Hi,
react fragment removed from the ProfileInfo.jsx page
Please review and merge this PR and close the BUG-0030
> React fragment removed 

- src/Components/Home Page Components/AwarenessSection.jsx
Hi, 
@Subhratanu @Sabbir45ali @EmrysILIO1710  
Please review and merge thus PR and close the BUG-0032
> Text overflow issue fixed

- src/Components/Home Page Components/AwarenessSection.jsx
Hi,
Please review and merge thus PR and close the BUG-0035
> Text updated 

- src/Components/Profile Page Components/ProfileNav.jsx
- src/Components/Universal Components/Navbar.jsx
Hi,
Please review and merge thus PR and close the BUG-0031
> Url path fixed

- src/Components/Home Page Components/AwarenessSection.jsx
Hi,
The link to form page in text yourself updated
Please review and merge thus PR and close the BUG-0033
> Link Updated

- src/Components/HomePageMobileComponents/HomaPageHeader.jsx
Hi,
Please review and merge thus PR and close the BUG-0025
> Text position updated

- src/Components/HomePageMobileComponents/AwarenessMobile.jsx
Hi,
Please review and merge thus PR and close the BUG-0028
> Done updating issue

- src/Components/HomePageMobileComponents/AwarenessMobile.jsx
Hi,
Border radius issue updated in code line-20
Please review and merge thus PR and close the BUG-0027
> Updated border radius issue 

- src/Components/Home Page Components/AwarenessSection.jsx
Hi,
pink border is added in the home page boxes
Please review and merge this PR and close the BUG-0036 issue
> Box design issue fixed in the home page[desktop version]

- src/Components/Home Page Components/AwarenessSection.jsx
Hi,
Please review and merge this PR and close the issue BUG-0039
> Corner radius issue fixed in the home page[Desktop version]

- src/Components/Home Page Components/HomePageFooter.jsx
Hi,
Please review and merge thus PR and close the BUG-0037
> Information Updated in Footer

- src/App.jsx
- src/pages/FormPage_Mobile/FormPage_Mobile.jsx
Hi,
Please review and merge this PR 
CC:
@Sayanipal2004 @TitlyC06
> Create form page and add bg image [Mobile version].

- src/pages/FormPage/FormPage.jsx
Hi,
Please review and merge this PR 
CC
@Sayanipal2004 @TitlyC06
> Add bg in form page [Desktop version].

- src/Components/Form Page Components/FormButtons.jsx
- src/Components/Form Page Components/FormLeftModal.jsx
> Buttons added in the form page LeftModal

- src/App.css
- src/Components/ProfilePage Mobile Components/ProfilePageMobileMainModal.jsx
- src/Components/ProfilePage Mobile Components/ProfilePageNav.jsx
- src/Components/ProfilePage Mobile Components/RichDataMobile.jsx
Hi @Subhratanu @EmrysILIO1710 @Sabbir45ali
CC- @Sayanipal2004 @PayalRoy2004
> BCD 0039 RichDataModalMobile

- src/Components/SignInPage_Mobile_Components/SignInPage_Footer.jsx
Hi,,
@Subhratanu @EmrysILIO1710 @Sabbir45ali 
Please review and merge this PR and close the issue BUG-0042
cc- @TitlyC06 @PayalRoy2004
> URL issue fixed in the SignIn page [responsive version]

- src/Components/SignInPage_Mobile_Components/SignInPage_Button.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_Footer.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_bg.jsx
- src/pages/SignUpPageMobile/SignUpPageMobile.jsx
Sign up page for responsive version is completed.
Hi,,
@Sabbir45ali @EmrysILIO1710 
Please review and merge this PR and close the issue BUG-0041
> SignUp page[responsive version] completed

- src/App.jsx
- src/Components/Profile Page Components/MainModalProfile.jsx
- src/pages/Profile Page Mobile/ProfilePageMobile.jsx
- src/pages/YesPage/YesPage.jsx
Hi,
Please review and merge thus PR and close the BUG-0058
@Sayanipal2004 @PayalRoy2004
> YesPage added and navbar added

- src/App.jsx
- src/Components/HomePageMobileComponents/AwarenessMobile.jsx
- src/Components/ProfilePage Mobile Components/RichDataMobile.jsx
> form page is linked with the test yourself button[responsive version]

- src/App.jsx
- src/Components/Sign Up page Component/SignUpPageRightModel/Dropdown.jsx
- src/Components/Sign Up page Component/SignUpPageRightModel/Input.jsx
- src/Components/Sign Up page Component/SignUpPageRightModel/MainRightModel.jsx
- src/Components/SignIn page Component/SignInInput.jsx
- src/Components/SignIn page Component/SignInMainModal.jsx
- src/pages/signuppage/Signup.jsx
> DropdownMenu added in SignUp and SignIn page[Desktop version]

- src/App.css
- src/pages/YesPage/YesPage.jsx
Add bg in Yes Page (Desktop)
Hi,
Please review and merge this PR.
CC:
@TitlyC06 @Sayanipal2004
> Add bg in YesPage

- src/Components/Home Page Components/HomePageFooter.jsx
Hi,
Please review and merge this PR and close the issue BUG-0046
> The phone icon direction is corrected in HomePage Footer[Desktop version]

- src/Components/ProfilePage Mobile Components/ProfilePageNav.jsx
Hi,
The log out button is updated.
Please review and merge thus PR and close the BUGFIX-0044
> Bugfix-0044

- src/Components/Form Page Components/FormPageNavbar.jsx
- src/Components/ProfilePage Mobile Components/RichDataMobile.jsx
- src/pages/FormPage_Mobile/FormPage_Mobile.jsx
Added Navbar in FormPage (mobile version)
Hii
CC: @TitlyC06 @Sayanipal2004
> Added Navbar in FormPage.

- src/Components/Form Page Components/FormLeftModal.jsx
- src/pages/FormPage/FormPage.jsx
Add left section in form page desktop 
Hii
@Subhratanu @EmrysILIO1710 @Sabbir45ali 
CC: @TitlyC06 @Sayanipal2004
> Add left section in form page.

- src/Components/Form Page Components/FormRightModel.jsx
- src/pages/FormPage/FormPage.jsx
Hi @Subhratanu @EmrysILIO1710 
Please review and merge this pr BCD-0045
@Sayanipal2004 @PayalRoy2004 @Sabbir45ali
> FormRightSectionDone

- src/Components/FormpageMobileComponenets/FormCard.jsx
- src/Components/FormpageMobileComponenets/SideButton.jsx
- src/pages/FormPage_Mobile/FormPage_Mobile.jsx
> Check section in the form page[Mobile version] created

- src/App.css
- src/App.jsx
- src/pages/FormPageBtoC/FormPageBtoC.jsx
Add bg in form page for single customer [Desktop version]
Hi,
CC: @TitlyC06 @Sayanipal2004
> Added Navbar at Single Customer form

- src/Components/Form Page Components/FormLeftModal.jsx
- src/Components/Form Page Components/FormRightModel.jsx
- src/Components/Universal Components/Navbar.jsx
- src/pages/FormPage/FormPage.jsx
Hi,
@Sabbir45ali 
The form page is fixed. Now the left and right modal is rendering correctly.
Please review and merge this PR and close the BUG-0047
> Form page is fixed

- src/App.jsx
- src/pages/FormPageBtoC_Mobile/FormPageBtoC_Mobile.jsx
Hi..
Form page for single customer is created and navbar is added.
> Form page for single customer [Mobile version]

- src/App.css
- src/pages/NoPage/NoPage.jsx
Hi @Subhratanu @EmrysILIO1710 @Sabbir45ali
CC- @Sayanipal2004  @PayalRoy2004
> No page bg added

- src/Components/NoPage/TextBox.jsx
Added text in No page.
Hii 
please review and merge this PR.
CC:
@TitlyC06 @Sayanipal2004
> NoPage done

- src/Components/Form Page BtoC Components/TextBoxBtoC.jsx
- src/pages/NoPage/NoPage.jsx
Added text and button on form page of Single customer
Hii 
please review and merge this PR.
CC:
@TitlyC06 @Sayanipal2004
> Added text on form page of Single customer

- src/Components/Sign Up page Component/SignUpPageRightModel/Dropdown.jsx
- src/Components/Sign Up page Component/SignUpPageRightModel/MainRightModel.jsx
- src/Components/SignIn page Component/SignInInput.jsx
Hii...!
"Admin" option is removed from dropdown in signup form[Desktop version]
Please review and merge this PR..
>  "Admin" option is removed from dropdown in signup form.

- src/App.css
- src/App.jsx
- src/pages/YeaPage_Mobile/YesPage_Mobile.jsx
Yes Page Mobile version created and added navbar and bg
Hii
CC:
@TitlyC06 @Sayanipal2004
> YesPage _Mobile version done

- src/Components/Profile Page Components/MainModalProfile.jsx
User Data table added in Profile page
Hii
Please review and merge these PR
CC:
@Sayanipal2004 @TitlyC06
> User data table added

- src/App.css
- src/App.jsx
- src/pages/NoPageMobile/NoPageMobile.jsx
Hi @Subhratanu @EmrysILIO1710 @Sabbir45ali
CC- @Sayanipal2004 @JOY-Singha-03 @PayalRoy2004
> NoPageResponsiveDone

- src/App.jsx
> chore: remove commented-out deployment code from App component

- src/App.css
- src/Components/SignIn page Component/SignInMainModal.jsx
- src/Components/SignInPage_Mobile_Components/SignInPage_bg.jsx
- src/Components/Universal Components/Cross.jsx
- src/Components/Universal Components/ForgotPasswordModal.jsx
- src/Components/Universal Components/OtpResultModal.jsx
- src/Components/Universal Components/Tick.jsx
> OTP result is created
